model_selection:
    model:
      XGBClassifier:
        search_param_grid:
          max_depth:
          - 3
          - 5
          - 7
          - 9
          - 11
          n_estimators:
          - 50
          - 100
          - 130
          random_state:
            - 0
            - 50
            - 100

      GaussianNB:
        search_param_grid:
          var_smoothing:
            - 0.5
            - 0.05
            - 0.01

      LogisticRegression:
        search_param_grid:
          C:
            - 500
            - 1000
          max_iter:
            - 100
            - 113
          multi_class:
            - 'auto'
          penalty:
            - 'l2'
          solver:
            - 'lbfgs'
            - 'liblinear'
            - 'sag'
            - 'saga'

      RandomForestClassifier:  
        search_param_grid:    
          n_estimators:      
            - 100      
            - 200      
            - 300    
          max_depth:      
            - 10      
            - 20     
            - 30      
          min_samples_split:      
            - 2      
            - 5      
            - 10    
          min_samples_leaf:      
            - 1      
            - 2      
            - 4    
          bootstrap:      
            - True      
            - False
      
      SVC:
        search_param_grid:
          C:
            - 0.1
            - 1
            - 10
            - 100
          kernel:
            - 'linear'
            - 'rbf'
            - 'poly'
          degree:
            - 3
            - 4
            - 5
          gamma:
            - 'scale'
            - 'auto'
      
      ANN:
        search_param_grid:
          epochs:
            - 10
            - 20
            - 40
            - 60
          batch_size:
            - 32
            - 64
          build_fn__layers:
            - (128, 64, 32)
            - (256, 128, 64)
          build_fn__learning_rate:
            - 0.01
            - 0.001